### PR TITLE
Added code for recaptcha fix

### PR DESCRIPTION
**Pull request by portableant**

### CODE REVIEW

**Comment by s-moon** [comment]
Thank you for this @portableant. Unfortunately, it didn't work. I switched out the keys, used the local ones etc. and no luck.

**Comment by portableant** [comment]
Do you still get the V1 deprecation message? This is what I get with the testing keys on my machine:

screen shot 2018-05-25 at 15 29 46

**Comment by s-moon** [comment]
No, still the V1 for me. Your image would have encouraged me enormously :-)

**Comment by portableant** [comment]
Asking a dumb question, you did switch to this branch to test? The code is significantly different.

**Comment by s-moon** [comment]
No, not dumb :-) Yes I did. I confirmed it by looking for some specific
changes based on the commit. I also tried (forcing) the test keys and newly
generated keys (v2) too.

One thing I did get was a weird JS error with the test keys. I'd have to
reproduce to show you tho and can't at the moment.

**Comment by s-moon** [comment]
Code replicated and modified slightly. Credit goes to @portableant for the hard parts. Now working.

closes #1175

**Pull request closed without merging**
